//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.BusinessLayer.DataLayerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Participation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsercodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CourseCode {
            get {
                return this.CourseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCodeField, value) != true)) {
                    this.CourseCodeField = value;
                    this.RaisePropertyChanged("CourseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usercode {
            get {
                return this.UsercodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UsercodeField, value) != true)) {
                    this.UsercodeField = value;
                    this.RaisePropertyChanged("Usercode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity))]
    public partial class SurveyEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyID {
            get {
                return this.SurveyIDField;
            }
            set {
                if ((this.SurveyIDField.Equals(value) != true)) {
                    this.SurveyIDField = value;
                    this.RaisePropertyChanged("SurveyID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyInstanceEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    public partial class SurveyInstanceEntity : Survey.BusinessLayer.DataLayerServiceReference.SurveyEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Survey.BusinessLayer.DataLayerServiceReference.QuestionInstanceEntity> QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyInstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsercodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseCode {
            get {
                return this.CourseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCodeField, value) != true)) {
                    this.CourseCodeField = value;
                    this.RaisePropertyChanged("CourseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Survey.BusinessLayer.DataLayerServiceReference.QuestionInstanceEntity> Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyInstanceID {
            get {
                return this.SurveyInstanceIDField;
            }
            set {
                if ((this.SurveyInstanceIDField.Equals(value) != true)) {
                    this.SurveyInstanceIDField = value;
                    this.RaisePropertyChanged("SurveyInstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usercode {
            get {
                return this.UsercodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UsercodeField, value) != true)) {
                    this.UsercodeField = value;
                    this.RaisePropertyChanged("Usercode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionInstanceEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    public partial class QuestionInstanceEntity : Survey.BusinessLayer.DataLayerServiceReference.QuestionEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionInstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyInstanceIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionInstanceID {
            get {
                return this.QuestionInstanceIDField;
            }
            set {
                if ((this.QuestionInstanceIDField.Equals(value) != true)) {
                    this.QuestionInstanceIDField = value;
                    this.RaisePropertyChanged("QuestionInstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyInstanceID {
            get {
                return this.SurveyInstanceIDField;
            }
            set {
                if ((this.SurveyInstanceIDField.Equals(value) != true)) {
                    this.SurveyInstanceIDField = value;
                    this.RaisePropertyChanged("SurveyInstanceID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Survey.BusinessLayer.DataLayerServiceReference.QuestionInstanceEntity))]
    public partial class QuestionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyID {
            get {
                return this.SurveyIDField;
            }
            set {
                if ((this.SurveyIDField.Equals(value) != true)) {
                    this.SurveyIDField = value;
                    this.RaisePropertyChanged("SurveyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataLayerServiceReference.ISurveyDLServices")]
    public interface ISurveyDLServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyDLServices/GetCourseByUserCode", ReplyAction="http://tempuri.org/ISurveyDLServices/GetCourseByUserCodeResponse")]
        System.Collections.Generic.List<Survey.BusinessLayer.DataLayerServiceReference.Participation> GetCourseByUserCode(string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyDLServices/GetSurveyByCourseCode", ReplyAction="http://tempuri.org/ISurveyDLServices/GetSurveyByCourseCodeResponse")]
        Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity GetSurveyByCourseCode(string courseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyDLServices/InsertSurveyInstance", ReplyAction="http://tempuri.org/ISurveyDLServices/InsertSurveyInstanceResponse")]
        int InsertSurveyInstance(Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity survey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyDLServices/InsertQuestionInstance", ReplyAction="http://tempuri.org/ISurveyDLServices/InsertQuestionInstanceResponse")]
        int InsertQuestionInstance(Survey.BusinessLayer.DataLayerServiceReference.QuestionInstanceEntity question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyDLServices/GetSurveyInstancesByParticipation", ReplyAction="http://tempuri.org/ISurveyDLServices/GetSurveyInstancesByParticipationResponse")]
        Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity GetSurveyInstancesByParticipation(Survey.BusinessLayer.DataLayerServiceReference.Participation participation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyDLServices/GetSurveyInfoByCourseCode", ReplyAction="http://tempuri.org/ISurveyDLServices/GetSurveyInfoByCourseCodeResponse")]
        Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity GetSurveyInfoByCourseCode(string courseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyDLServices/GetTotalNumberOfStudentsByCourseCode", ReplyAction="http://tempuri.org/ISurveyDLServices/GetTotalNumberOfStudentsByCourseCodeResponse" +
            "")]
        int GetTotalNumberOfStudentsByCourseCode(string courseCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISurveyDLServicesChannel : Survey.BusinessLayer.DataLayerServiceReference.ISurveyDLServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SurveyDLServicesClient : System.ServiceModel.ClientBase<Survey.BusinessLayer.DataLayerServiceReference.ISurveyDLServices>, Survey.BusinessLayer.DataLayerServiceReference.ISurveyDLServices {
        
        public SurveyDLServicesClient() {
        }
        
        public SurveyDLServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SurveyDLServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyDLServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyDLServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Survey.BusinessLayer.DataLayerServiceReference.Participation> GetCourseByUserCode(string userCode) {
            return base.Channel.GetCourseByUserCode(userCode);
        }
        
        public Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity GetSurveyByCourseCode(string courseCode) {
            return base.Channel.GetSurveyByCourseCode(courseCode);
        }
        
        public int InsertSurveyInstance(Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity survey) {
            return base.Channel.InsertSurveyInstance(survey);
        }
        
        public int InsertQuestionInstance(Survey.BusinessLayer.DataLayerServiceReference.QuestionInstanceEntity question) {
            return base.Channel.InsertQuestionInstance(question);
        }
        
        public Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity GetSurveyInstancesByParticipation(Survey.BusinessLayer.DataLayerServiceReference.Participation participation) {
            return base.Channel.GetSurveyInstancesByParticipation(participation);
        }
        
        public Survey.BusinessLayer.DataLayerServiceReference.SurveyInstanceEntity GetSurveyInfoByCourseCode(string courseCode) {
            return base.Channel.GetSurveyInfoByCourseCode(courseCode);
        }
        
        public int GetTotalNumberOfStudentsByCourseCode(string courseCode) {
            return base.Channel.GetTotalNumberOfStudentsByCourseCode(courseCode);
        }
    }
}
