///////////////////////////////////////////////////////////
//  SurveyEntity.cs
//  Implementation of the Class SurveyEntity
//  Generated by Enterprise Architect
//  Created on:      26-¾ÅÔÂ-2009 16:49:40
//  Original author: Shawn Jiang
///////////////////////////////////////////////////////////




using System;

namespace cosc365Assignment2.DataEntities {
	public class SurveyEntity {

		public string CourseCode;
		public DateTime EndDate;
		public DateTime StartDate;

		public SurveyEntity(){

		}

	}//end SurveyEntity

}//end namespace cosc365Assignment2.DataEntities