//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.DataLayer.CourseInfoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Participation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsercodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CourseCode {
            get {
                return this.CourseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCodeField, value) != true)) {
                    this.CourseCodeField = value;
                    this.RaisePropertyChanged("CourseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usercode {
            get {
                return this.UsercodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UsercodeField, value) != true)) {
                    this.UsercodeField = value;
                    this.RaisePropertyChanged("Usercode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseInfoServiceReference.CourseInfoServiceSoap")]
    public interface CourseInfoServiceSoap {
        
        // CODEGEN: Generating message contract since element name userCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourseByUserCode", ReplyAction="*")]
        Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeResponse GetCourseByUserCode(Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeRequest request);
        
        // CODEGEN: Generating message contract since element name courseCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourseByCourseCode", ReplyAction="*")]
        Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeResponse GetCourseByCourseCode(Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeRequest request);
        
        // CODEGEN: Generating message contract since element name courseCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalNumberOfStudentsByCourseCode", ReplyAction="*")]
        Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeResponse GetTotalNumberOfStudentsByCourseCode(Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseByUserCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseByUserCode", Namespace="http://tempuri.org/", Order=0)]
        public Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeRequestBody Body;
        
        public GetCourseByUserCodeRequest() {
        }
        
        public GetCourseByUserCodeRequest(Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseByUserCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userCode;
        
        public GetCourseByUserCodeRequestBody() {
        }
        
        public GetCourseByUserCodeRequestBody(string userCode) {
            this.userCode = userCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseByUserCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseByUserCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeResponseBody Body;
        
        public GetCourseByUserCodeResponse() {
        }
        
        public GetCourseByUserCodeResponse(Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseByUserCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Survey.DataLayer.CourseInfoServiceReference.Participation> GetCourseByUserCodeResult;
        
        public GetCourseByUserCodeResponseBody() {
        }
        
        public GetCourseByUserCodeResponseBody(System.Collections.Generic.List<Survey.DataLayer.CourseInfoServiceReference.Participation> GetCourseByUserCodeResult) {
            this.GetCourseByUserCodeResult = GetCourseByUserCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseByCourseCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseByCourseCode", Namespace="http://tempuri.org/", Order=0)]
        public Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeRequestBody Body;
        
        public GetCourseByCourseCodeRequest() {
        }
        
        public GetCourseByCourseCodeRequest(Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseByCourseCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string courseCode;
        
        public GetCourseByCourseCodeRequestBody() {
        }
        
        public GetCourseByCourseCodeRequestBody(string courseCode) {
            this.courseCode = courseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseByCourseCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseByCourseCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeResponseBody Body;
        
        public GetCourseByCourseCodeResponse() {
        }
        
        public GetCourseByCourseCodeResponse(Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseByCourseCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Survey.DataLayer.CourseInfoServiceReference.Course GetCourseByCourseCodeResult;
        
        public GetCourseByCourseCodeResponseBody() {
        }
        
        public GetCourseByCourseCodeResponseBody(Survey.DataLayer.CourseInfoServiceReference.Course GetCourseByCourseCodeResult) {
            this.GetCourseByCourseCodeResult = GetCourseByCourseCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalNumberOfStudentsByCourseCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalNumberOfStudentsByCourseCode", Namespace="http://tempuri.org/", Order=0)]
        public Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeRequestBody Body;
        
        public GetTotalNumberOfStudentsByCourseCodeRequest() {
        }
        
        public GetTotalNumberOfStudentsByCourseCodeRequest(Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalNumberOfStudentsByCourseCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string courseCode;
        
        public GetTotalNumberOfStudentsByCourseCodeRequestBody() {
        }
        
        public GetTotalNumberOfStudentsByCourseCodeRequestBody(string courseCode) {
            this.courseCode = courseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalNumberOfStudentsByCourseCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalNumberOfStudentsByCourseCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeResponseBody Body;
        
        public GetTotalNumberOfStudentsByCourseCodeResponse() {
        }
        
        public GetTotalNumberOfStudentsByCourseCodeResponse(Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalNumberOfStudentsByCourseCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTotalNumberOfStudentsByCourseCodeResult;
        
        public GetTotalNumberOfStudentsByCourseCodeResponseBody() {
        }
        
        public GetTotalNumberOfStudentsByCourseCodeResponseBody(int GetTotalNumberOfStudentsByCourseCodeResult) {
            this.GetTotalNumberOfStudentsByCourseCodeResult = GetTotalNumberOfStudentsByCourseCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CourseInfoServiceSoapChannel : Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CourseInfoServiceSoapClient : System.ServiceModel.ClientBase<Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap>, Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap {
        
        public CourseInfoServiceSoapClient() {
        }
        
        public CourseInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeResponse Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap.GetCourseByUserCode(Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeRequest request) {
            return base.Channel.GetCourseByUserCode(request);
        }
        
        public System.Collections.Generic.List<Survey.DataLayer.CourseInfoServiceReference.Participation> GetCourseByUserCode(string userCode) {
            Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeRequest inValue = new Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeRequest();
            inValue.Body = new Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeRequestBody();
            inValue.Body.userCode = userCode;
            Survey.DataLayer.CourseInfoServiceReference.GetCourseByUserCodeResponse retVal = ((Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap)(this)).GetCourseByUserCode(inValue);
            return retVal.Body.GetCourseByUserCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeResponse Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap.GetCourseByCourseCode(Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeRequest request) {
            return base.Channel.GetCourseByCourseCode(request);
        }
        
        public Survey.DataLayer.CourseInfoServiceReference.Course GetCourseByCourseCode(string courseCode) {
            Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeRequest inValue = new Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeRequest();
            inValue.Body = new Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeRequestBody();
            inValue.Body.courseCode = courseCode;
            Survey.DataLayer.CourseInfoServiceReference.GetCourseByCourseCodeResponse retVal = ((Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap)(this)).GetCourseByCourseCode(inValue);
            return retVal.Body.GetCourseByCourseCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeResponse Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap.GetTotalNumberOfStudentsByCourseCode(Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeRequest request) {
            return base.Channel.GetTotalNumberOfStudentsByCourseCode(request);
        }
        
        public int GetTotalNumberOfStudentsByCourseCode(string courseCode) {
            Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeRequest inValue = new Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeRequest();
            inValue.Body = new Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeRequestBody();
            inValue.Body.courseCode = courseCode;
            Survey.DataLayer.CourseInfoServiceReference.GetTotalNumberOfStudentsByCourseCodeResponse retVal = ((Survey.DataLayer.CourseInfoServiceReference.CourseInfoServiceSoap)(this)).GetTotalNumberOfStudentsByCourseCode(inValue);
            return retVal.Body.GetTotalNumberOfStudentsByCourseCodeResult;
        }
    }
}
