//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Client.BusinessLayerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyInstanceEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    public partial class SurveyInstanceEntity : Survey.Client.BusinessLayerServiceReference.SurveyEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Survey.Client.BusinessLayerServiceReference.QuestionInstanceEntity> QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyInstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseCode {
            get {
                return this.CourseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCodeField, value) != true)) {
                    this.CourseCodeField = value;
                    this.RaisePropertyChanged("CourseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Survey.Client.BusinessLayerServiceReference.QuestionInstanceEntity> Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyInstanceID {
            get {
                return this.SurveyInstanceIDField;
            }
            set {
                if ((this.SurveyInstanceIDField.Equals(value) != true)) {
                    this.SurveyInstanceIDField = value;
                    this.RaisePropertyChanged("SurveyInstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Survey.Client.BusinessLayerServiceReference.SurveyInstanceEntity))]
    public partial class SurveyEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyID {
            get {
                return this.SurveyIDField;
            }
            set {
                if ((this.SurveyIDField.Equals(value) != true)) {
                    this.SurveyIDField = value;
                    this.RaisePropertyChanged("SurveyID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionInstanceEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    public partial class QuestionInstanceEntity : Survey.Client.BusinessLayerServiceReference.QuestionEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionInstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyInstanceIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionInstanceID {
            get {
                return this.QuestionInstanceIDField;
            }
            set {
                if ((this.QuestionInstanceIDField.Equals(value) != true)) {
                    this.QuestionInstanceIDField = value;
                    this.RaisePropertyChanged("QuestionInstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyInstanceID {
            get {
                return this.SurveyInstanceIDField;
            }
            set {
                if ((this.SurveyInstanceIDField.Equals(value) != true)) {
                    this.SurveyInstanceIDField = value;
                    this.RaisePropertyChanged("SurveyInstanceID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionEntity", Namespace="http://schemas.datacontract.org/2004/07/Survey.DataEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Survey.Client.BusinessLayerServiceReference.QuestionInstanceEntity))]
    public partial class QuestionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyID {
            get {
                return this.SurveyIDField;
            }
            set {
                if ((this.SurveyIDField.Equals(value) != true)) {
                    this.SurveyIDField = value;
                    this.RaisePropertyChanged("SurveyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessLayerServiceReference.ISurveyBLServices")]
    public interface ISurveyBLServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyBLServices/GetCourseByUserCode", ReplyAction="http://tempuri.org/ISurveyBLServices/GetCourseByUserCodeResponse")]
        System.Collections.Generic.List<Survey.Client.BusinessLayerServiceReference.SurveyInstanceEntity> GetCourseByUserCode(string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyBLServices/GetSurveyByCourseCode", ReplyAction="http://tempuri.org/ISurveyBLServices/GetSurveyByCourseCodeResponse")]
        Survey.Client.BusinessLayerServiceReference.SurveyInstanceEntity GetSurveyByCourseCode(string courseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyBLServices/InsertSurveyInstance", ReplyAction="http://tempuri.org/ISurveyBLServices/InsertSurveyInstanceResponse")]
        int InsertSurveyInstance(Survey.Client.BusinessLayerServiceReference.SurveyInstanceEntity survey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISurveyBLServicesChannel : Survey.Client.BusinessLayerServiceReference.ISurveyBLServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SurveyBLServicesClient : System.ServiceModel.ClientBase<Survey.Client.BusinessLayerServiceReference.ISurveyBLServices>, Survey.Client.BusinessLayerServiceReference.ISurveyBLServices {
        
        public SurveyBLServicesClient() {
        }
        
        public SurveyBLServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SurveyBLServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyBLServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyBLServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Survey.Client.BusinessLayerServiceReference.SurveyInstanceEntity> GetCourseByUserCode(string userCode) {
            return base.Channel.GetCourseByUserCode(userCode);
        }
        
        public Survey.Client.BusinessLayerServiceReference.SurveyInstanceEntity GetSurveyByCourseCode(string courseCode) {
            return base.Channel.GetSurveyByCourseCode(courseCode);
        }
        
        public int InsertSurveyInstance(Survey.Client.BusinessLayerServiceReference.SurveyInstanceEntity survey) {
            return base.Channel.InsertSurveyInstance(survey);
        }
    }
}
